// Calculator and app-shell wording in English and Bangla.
export type Lang = 'en' | 'bn'

const en = {
  tabs: { home: 'Home', results: 'Results', market: 'Market', plan: 'Plan', packages: 'Packages', calc: 'Calculator' },
  nav: { overview: 'Overview', about: 'About us', results: 'Results', market: 'Market', why: 'Why us', plan: '6-month plan', calculator: 'Profit calculator', packages: 'Packages', start: 'Get started' },
  short: { overview: 'Home', results: 'Results', plan: 'Plan', calculator: 'Profit', packages: 'Packages' },
  ctaTitle: 'Ready to grow your business?', ctaText: 'Book a free meeting. We will look at your business, answer your questions and agree the right package for you.', ctaBtn: 'Chat on WhatsApp', ctaWeb: 'Book a free consultation',
  side: { kicker: 'Project proposal', title: '6-month growth plan', contents: 'Contents', close: 'Close', pdf: 'Download PDF', talk: 'Chat on WhatsApp', read: 'read' },
  calcTitle: 'Ads profit calculator',
  calcSub: 'Pick your business type, set your budget and see exactly what your ads can return: orders, sales, costs and profit, month by month.',
  presetsLabel: 'Your business type',
  presets: { food: 'Food & snacks', beauty: 'Beauty & cosmetics', fashion: 'Fashion & clothing', gadgets: 'Gadgets & electronics', home: 'Home & furniture', services: 'Local services', custom: 'Custom' },
  groups: { budget: 'Budget', product: 'Your product', ads: 'Ad performance', costs: 'Delivery & returns', repeat: 'Repeat customers', growth: 'SEO & growth' },
  f: {
    budgetUsd: 'Monthly ad budget', fx: 'Exchange rate (Tk per $1)', aov: 'Average order value', margin: 'Profit margin on product',
    cpm: 'Cost per 1,000 views (CPM)', ctr: 'Click rate (CTR)', cvr: 'Conversion rate', returnRate: 'Returned / refused orders',
    returnCost: 'Loss per returned order', deliveryCost: 'Delivery cost you pay per order', paymentFee: 'Payment fee',
    repeatShare: 'Customers who buy again', repeatOrders: 'Extra orders per returning customer', seoOn: 'Include SEO visitors',
    seoVisitors: 'SEO visitors a month (by Month 6)', agencyFee: 'Monthly service fee (optional)', autoScale: 'Raise budget when profitable', scalePct: 'Increase per month',
  },
  hints: {
    budgetUsd: 'Minimum $50. Paid directly to Meta / Google.', margin: 'Selling price minus product cost, as a % of price.',
    cpm: 'Bangladesh: about Tk 30–230 (2025–26).', ctr: 'Share of viewers who click. 1–2% is typical.', cvr: 'Share of visitors who order.',
    returnRate: 'Cash-on-delivery orders the customer refuses.', returnCost: 'Usually two-way delivery, about Tk 100–150.',
    deliveryCost: 'Leave 0 if the customer pays delivery.', agencyFee: 'Leave 0 to see results before our fee.',
  },
  steady: 'Your typical month', steadySub: 'Once ads are optimized and buyers start coming back',
  verdict: { profit: 'Profitable', thin: 'Break-even', loss: 'Not profitable yet' },
  k: {
    netProfit: 'Net profit / month', revenue: 'Sales / month', orders: 'Orders / month', roas: 'Ad return (ROAS)', roi: 'Return on investment',
    cpa: 'Cost per new customer', mer: 'Total sales ÷ ad spend',
  },
  funnel: 'From ad money to orders', fv: { spend: 'Ad spend', views: 'Ad views', clicks: 'Clicks', orders: 'New orders', repeat: 'Repeat orders', delivered: 'Delivered' },
  perClick: 'per click',
  breakdown: 'Where the money goes', bd: { revenue: 'Sales', product: 'Product cost', fees: 'Payment fees', delivery: 'Delivery', returns: 'Returns loss', ads: 'Ad spend', fee: 'Service fee', profit: 'Net profit' },
  health: 'Health check',
  h: {
    beCpa: 'Most you can pay for a new customer', beRoas: 'Break-even ad return', ltv: 'Customer lifetime profit',
    ltvCac: 'Lifetime profit ÷ customer cost', beCvr: 'Conversion rate needed to break even', cover: 'Ad budget to cover the service fee',
    learning: 'New orders from ads per week',
  },
  learnOk: 'Enough orders for Meta to optimize quickly.',
  learnLow: 'Meta learns best with about 50 orders a week. At this budget we run one focused campaign so it still learns, just more slowly.',
  forecast: '6-month forecast', forecastSub: 'Ads learn, SEO grows, repeat buyers return. Budget rises only when ads are clearly profitable.',
  legend: { ads: 'New sales from ads', seo: 'Sales from SEO', repeat: 'Repeat customers', profit: 'Net profit' },
  t: { month: 'Month', budget: 'Budget', orders: 'Orders', revenue: 'Sales', profit: 'Net profit', cumulative: 'Running total', roas: 'ROAS' },
  totals: { spend: 'Total ad spend', revenue: 'Total sales', profit: 'Total net profit', payback: 'Profitable from', none: 'Not within 6 months', monthN: 'Month' },
  budgets: 'Compare budgets', budgetsSub: 'Same business, different monthly budgets (typical month). Ad costs rise a little as budgets grow.',
  b: { budget: 'Budget', orders: 'Orders', revenue: 'Sales', profit: 'Net profit', roi: 'ROI' },
  how: 'How we calculate',
  howList: [
    'Ad spend (Tk) = budget ($) × exchange rate.',
    'Ad views = spend ÷ CPM × 1,000. CPM rises 10% for every doubling of budget above $500.',
    'Clicks = views × click rate. New orders = clicks × conversion rate.',
    'Repeat orders = new customers × % who buy again × extra orders. They cost no ad money.',
    'Delivered orders = all orders − returned orders. Sales = delivered orders × average order value.',
    'Net profit = sales − product cost − payment fees − delivery − returns loss − ad spend − service fee.',
    'Ad return (ROAS) = first-order sales from ads ÷ ad spend. Break-even ROAS = order value ÷ profit per order.',
    'Forecast: conversion rate starts at 70% of your input and reaches 115% by Month 6 as we optimize; SEO reaches full traffic by Month 6.',
  ],
  disclaimer: 'Estimates for planning, not a promise. Real results depend on your product, price, offer and market. Starting values are typical for Bangladesh in 2025–26.',
  reset: 'Reset', usd: 'US$', perMonth: '/ month', on: 'On', off: 'Off', learnMore: 'Show details',
  openCalc: 'Open the profit calculator', months: 'months', tk: 'Tk',
}

const bn: typeof en = {
  tabs: { home: 'হোম', results: 'ফলাফল', market: 'বাজার', plan: 'পরিকল্পনা', packages: 'প্যাকেজ', calc: 'ক্যালকুলেটর' },
  nav: { overview: 'সারসংক্ষেপ', about: 'আমাদের কথা', results: 'ফলাফল', market: 'বাজার', why: 'কেন আমরা', plan: '৬ মাসের পরিকল্পনা', calculator: 'লাভের হিসাব', packages: 'প্যাকেজ', start: 'শুরু করুন' },
  short: { overview: 'হোম', results: 'ফলাফল', plan: 'পরিকল্পনা', calculator: 'লাভ', packages: 'প্যাকেজ' },
  ctaTitle: 'আপনার ব্যবসা বাড়াতে প্রস্তুত?', ctaText: 'একটি ফ্রি মিটিং বুক করুন। আমরা আপনার ব্যবসা দেখব, প্রশ্নের উত্তর দেব আর আপনার জন্য সঠিক প্যাকেজ ঠিক করব।', ctaBtn: 'WhatsApp-এ কথা বলুন', ctaWeb: 'ফ্রি পরামর্শ বুক করুন',
  side: { kicker: 'প্রজেক্ট প্রস্তাবনা', title: '৬ মাসের গ্রোথ প্ল্যান', contents: 'সূচিপত্র', close: 'বন্ধ করুন', pdf: 'PDF ডাউনলোড', talk: 'WhatsApp-এ কথা বলুন', read: 'পড়া হয়েছে' },
  calcTitle: 'অ্যাড প্রফিট ক্যালকুলেটর',
  calcSub: 'আপনার ব্যবসার ধরন বেছে নিন, বাজেট দিন, আর দেখুন অ্যাড থেকে ঠিক কী আসতে পারে: অর্ডার, বিক্রি, খরচ আর লাভ, মাস ধরে।',
  presetsLabel: 'আপনার ব্যবসার ধরন',
  presets: { food: 'খাবার ও স্ন্যাকস', beauty: 'বিউটি ও কসমেটিকস', fashion: 'ফ্যাশন ও পোশাক', gadgets: 'গ্যাজেট ও ইলেকট্রনিক্স', home: 'ঘর ও ফার্নিচার', services: 'লোকাল সার্ভিস', custom: 'নিজের মতো' },
  groups: { budget: 'বাজেট', product: 'আপনার পণ্য', ads: 'অ্যাডের পারফরম্যান্স', costs: 'ডেলিভারি ও রিটার্ন', repeat: 'রিপিট ক্রেতা', growth: 'SEO ও গ্রোথ' },
  f: {
    budgetUsd: 'মাসিক অ্যাড বাজেট', fx: 'বিনিময় হার ($1 = ৳)', aov: 'গড় অর্ডার মূল্য', margin: 'পণ্যে লাভের হার',
    cpm: 'প্রতি 1,000 ভিউয়ের খরচ (CPM)', ctr: 'ক্লিকের হার (CTR)', cvr: 'কেনার হার', returnRate: 'রিটার্ন / ফেরত দেওয়া অর্ডার',
    returnCost: 'প্রতি রিটার্নে ক্ষতি', deliveryCost: 'প্রতি অর্ডারে আপনার ডেলিভারি খরচ', paymentFee: 'পেমেন্ট ফি',
    repeatShare: 'যে ক্রেতারা আবার কেনেন', repeatOrders: 'ফিরে আসা ক্রেতার অতিরিক্ত অর্ডার', seoOn: 'SEO ভিজিটর যোগ করুন',
    seoVisitors: 'মাসে SEO ভিজিটর (মাস 6-এ)', agencyFee: 'মাসিক সার্ভিস ফি (ঐচ্ছিক)', autoScale: 'লাভ হলে বাজেট বাড়ান', scalePct: 'প্রতি মাসে বৃদ্ধি',
  },
  hints: {
    budgetUsd: 'সর্বনিম্ন $50। সরাসরি Meta / Google-কে পরিশোধ।', margin: 'বিক্রয়মূল্য থেকে পণ্যের খরচ বাদে, দামের %।',
    cpm: 'বাংলাদেশে প্রায় ৳30–230 (2025–26)।', ctr: 'যারা দেখে তাদের মধ্যে কতজন ক্লিক করে। 1–2% স্বাভাবিক।', cvr: 'ভিজিটরদের মধ্যে কতজন অর্ডার করে।',
    returnRate: 'ক্যাশ অন ডেলিভারিতে ক্রেতা যে অর্ডার নেন না।', returnCost: 'সাধারণত দুই দিকের ডেলিভারি, প্রায় ৳100–150।',
    deliveryCost: 'ক্রেতা ডেলিভারি চার্জ দিলে 0 রাখুন।', agencyFee: 'আমাদের ফি বাদে ফল দেখতে 0 রাখুন।',
  },
  steady: 'আপনার একটি সাধারণ মাস', steadySub: 'অ্যাড অপ্টিমাইজ হওয়ার পর আর ক্রেতারা ফিরে আসা শুরু করলে',
  verdict: { profit: 'লাভজনক', thin: 'লাভ-ক্ষতি সমান', loss: 'এখনো লাভজনক নয়' },
  k: {
    netProfit: 'নিট লাভ / মাস', revenue: 'বিক্রি / মাস', orders: 'অর্ডার / মাস', roas: 'অ্যাড রিটার্ন (ROAS)', roi: 'বিনিয়োগে রিটার্ন',
    cpa: 'প্রতি নতুন ক্রেতার খরচ', mer: 'মোট বিক্রি ÷ অ্যাড খরচ',
  },
  funnel: 'অ্যাডের টাকা থেকে অর্ডার পর্যন্ত', fv: { spend: 'অ্যাড খরচ', views: 'অ্যাড ভিউ', clicks: 'ক্লিক', orders: 'নতুন অর্ডার', repeat: 'রিপিট অর্ডার', delivered: 'ডেলিভারড' },
  perClick: 'প্রতি ক্লিক',
  breakdown: 'টাকা কোথায় যায়', bd: { revenue: 'বিক্রি', product: 'পণ্যের খরচ', fees: 'পেমেন্ট ফি', delivery: 'ডেলিভারি', returns: 'রিটার্নে ক্ষতি', ads: 'অ্যাড খরচ', fee: 'সার্ভিস ফি', profit: 'নিট লাভ' },
  health: 'স্বাস্থ্য পরীক্ষা',
  h: {
    beCpa: 'একজন নতুন ক্রেতার জন্য সর্বোচ্চ খরচ', beRoas: 'লাভ-ক্ষতি সমান অ্যাড রিটার্ন', ltv: 'একজন ক্রেতার মোট লাভ',
    ltvCac: 'মোট লাভ ÷ ক্রেতা পাওয়ার খরচ', beCvr: 'লাভ-ক্ষতি সমান করতে কেনার হার', cover: 'সার্ভিস ফি তুলতে দরকারি অ্যাড বাজেট',
    learning: 'প্রতি সপ্তাহে অ্যাড থেকে নতুন অর্ডার',
  },
  learnOk: 'Meta দ্রুত অপ্টিমাইজ করার মতো যথেষ্ট অর্ডার।',
  learnLow: 'Meta সপ্তাহে প্রায় 50টি অর্ডারে সবচেয়ে ভালো শেখে। এই বাজেটে আমরা একটি কেন্দ্রীভূত ক্যাম্পেইন চালাই, যাতে ধীরে হলেও শেখে।',
  forecast: '৬ মাসের পূর্বাভাস', forecastSub: 'অ্যাড শেখে, SEO বাড়ে, রিপিট ক্রেতা ফেরে। অ্যাড স্পষ্টভাবে লাভজনক হলে তবেই বাজেট বাড়ে।',
  legend: { ads: 'অ্যাড থেকে নতুন বিক্রি', seo: 'SEO থেকে বিক্রি', repeat: 'রিপিট ক্রেতা', profit: 'নিট লাভ' },
  t: { month: 'মাস', budget: 'বাজেট', orders: 'অর্ডার', revenue: 'বিক্রি', profit: 'নিট লাভ', cumulative: 'মোট (চলমান)', roas: 'ROAS' },
  totals: { spend: 'মোট অ্যাড খরচ', revenue: 'মোট বিক্রি', profit: 'মোট নিট লাভ', payback: 'লাভ শুরু', none: '৬ মাসের মধ্যে নয়', monthN: 'মাস' },
  budgets: 'বাজেট তুলনা', budgetsSub: 'একই ব্যবসা, আলাদা মাসিক বাজেট (সাধারণ মাস)। বাজেট বাড়লে অ্যাডের খরচ সামান্য বাড়ে।',
  b: { budget: 'বাজেট', orders: 'অর্ডার', revenue: 'বিক্রি', profit: 'নিট লাভ', roi: 'ROI' },
  how: 'আমরা যেভাবে হিসাব করি',
  howList: [
    'অ্যাড খরচ (৳) = বাজেট ($) × বিনিময় হার।',
    'অ্যাড ভিউ = খরচ ÷ CPM × 1,000। $500-এর ওপরে বাজেট প্রতি দ্বিগুণে CPM 10% বাড়ে।',
    'ক্লিক = ভিউ × ক্লিকের হার। নতুন অর্ডার = ক্লিক × কেনার হার।',
    'রিপিট অর্ডার = নতুন ক্রেতা × আবার কেনার % × অতিরিক্ত অর্ডার। এতে অ্যাড খরচ নেই।',
    'ডেলিভারড অর্ডার = সব অর্ডার − রিটার্ন। বিক্রি = ডেলিভারড অর্ডার × গড় অর্ডার মূল্য।',
    'নিট লাভ = বিক্রি − পণ্যের খরচ − পেমেন্ট ফি − ডেলিভারি − রিটার্নে ক্ষতি − অ্যাড খরচ − সার্ভিস ফি।',
    'অ্যাড রিটার্ন (ROAS) = অ্যাড থেকে প্রথম অর্ডারের বিক্রি ÷ অ্যাড খরচ। লাভ-ক্ষতি সমান ROAS = অর্ডার মূল্য ÷ প্রতি অর্ডারে লাভ।',
    'পূর্বাভাস: কেনার হার আপনার দেওয়া হারের 70% থেকে শুরু হয়ে মাস 6-এ 115%-এ পৌঁছায়; SEO মাস 6-এ পূর্ণ ভিজিটরে পৌঁছায়।',
  ],
  disclaimer: 'পরিকল্পনার জন্য অনুমান, প্রতিশ্রুতি নয়। আসল ফল নির্ভর করে আপনার পণ্য, দাম, অফার আর বাজারের ওপর। শুরুর মানগুলো 2025–26 সালের বাংলাদেশের সাধারণ হিসাব।',
  reset: 'রিসেট', usd: 'US$', perMonth: '/ মাস', on: 'চালু', off: 'বন্ধ', learnMore: 'বিস্তারিত দেখুন',
  openCalc: 'প্রফিট ক্যালকুলেটর খুলুন', months: 'মাস', tk: '৳',
}

export const STR = { en, bn }
export type Strings = typeof en
