// Canada site: services, homepage FAQ, city pages, proof and industries. Canadian English (neighbourhood, centre, licence).
// Keywords come from Google autocomplete research in Canada (gl=ca, Oct 2026), e.g. "seo company toronto",
// "local seo brampton", "mississauga seo agency", "web design calgary", "alberta seo agency", "ai seo agency canada".
import type { City, Faq, Service } from '../content'

export const CA_SERVICES: Service[] = [
  { id: 'local-seo', icon: 'pin', name: 'Local SEO & Google Maps', tagline: 'Win the Google Maps top three in the neighbourhoods you serve.',
    body: 'When someone in Scarborough, Brampton or the Beltline searches for your service, Google shows three businesses on the map and most people choose one of them. Our local SEO services align your Google Business Profile, website, reviews and Canadian directory listings so you appear in that top three for the jobs you want.',
    includes: ['Google Business Profile optimization, posts and photo updates', 'Canadian citations: Yelp.ca, YellowPages.ca, Canada411, Bing Places, Apple Business Connect', 'Service and neighbourhood pages that rank', 'Review requests and professional replies', 'Grid-based map ranking reports'],
    result: 'More calls and direction requests from Google Maps, without paying for every click.' },
  { id: 'google-ads', icon: 'ads', name: 'Google Ads management', tagline: 'Paid search that is measured in booked jobs, not clicks.',
    body: 'We plan and run Google Search, Performance Max and Local Services Ads campaigns around buyer keywords in your service area. Every call and form is tracked, irrelevant searches are blocked each week and budget moves to the postal codes and services that produce paying customers.',
    includes: ['Search, Performance Max and Local Services Ads setup', 'Postal-code and radius targeting for your service area', 'Landing pages built for calls and bookings', 'Call tracking and conversion tracking', 'Monthly report on leads, customers and cost in CAD'],
    result: 'Enquiries from the first month, with a cost per customer you can check.' },
  { id: 'seo', icon: 'search', name: 'Website SEO', tagline: 'Organic rankings for the searches that bring revenue.',
    body: 'Technical fixes, on-page work and helpful content written for Canadian customers. We research what people in your province actually type, build pages that answer it properly and earn links from relevant Canadian sites. No shortcuts that put your domain at risk.',
    includes: ['Keyword research by city and province', 'Technical SEO: speed, Core Web Vitals and indexing', 'On-page titles, headings and internal links', 'Service and guide content written by people', 'Links from relevant Canadian publications and associations'],
    result: 'Free organic traffic that compounds month after month.' },
  { id: 'web-design', icon: 'browser', name: 'Website design & development', tagline: 'Fast, accessible websites that turn visits into enquiries.',
    body: 'Custom websites in React, Next.js, WordPress or Shopify, designed mobile-first and built to load quickly on Canadian networks. We follow WCAG accessibility guidelines, which matters for AODA compliance in Ontario, and add click-to-call, quote forms and online booking where your customers expect them.',
    includes: ['Custom design, never a reused template', 'Mobile-first, fast-loading builds', 'WCAG 2.1 AA accessibility checks', 'SEO-ready structure and schema markup', 'Booking, quote forms and click-to-call'],
    result: 'A website that earns trust quickly and gets more people to pick up the phone.' },
  { id: 'web-apps', icon: 'app', name: 'Web app development', tagline: 'Custom tools that remove hours of admin.',
    body: 'When a website is not enough, we build web applications: customer portals, booking and dispatch systems, quote calculators and dashboards that connect to Jobber, Housecall Pro, QuickBooks, Jane or the other software your team already uses.',
    includes: ['Online booking and scheduling', 'Client and patient portals', 'Instant quote and price calculators', 'Dashboards and reporting', 'Integrations with your CRM and accounting tools'],
    result: 'Less paperwork, faster service and a smoother customer experience.' },
  { id: 'ai', icon: 'spark', name: 'AI SEO & AI search optimization', tagline: 'Be the business ChatGPT, Claude, Gemini and Google AI Overviews recommend.',
    body: 'Canadians now ask AI assistants which contractor, clinic or lawyer to call. Our AI SEO and generative engine optimization (GEO) work makes your business the clear, well-documented answer that ChatGPT, Claude, Gemini, Perplexity, Copilot and Google AI Overviews can confidently recommend for your services and city.',
    includes: ['ChatGPT SEO and AI assistant visibility', 'Google AI Overviews optimization', 'Structured data and entity optimization', 'Consistent business details across Canadian directories', 'Monthly AI visibility tracking'],
    result: 'Your name in AI answers, where most local competitors are still missing.' },
  { id: 'ai-agents', icon: 'bot', name: 'AI agents & AI receptionist', tagline: 'Every call, chat and lead answered within seconds, day and night.',
    body: 'An AI receptionist answers your phone and website chat in a natural voice, books appointments into your calendar, qualifies new enquiries and texts the details to your team. It can answer in English, French, Punjabi, Hindi, Mandarin and other languages your customers speak, so no caller reaches voicemail and moves on.',
    includes: ['AI receptionist and voice agent for inbound calls', 'Website, Facebook and Instagram chat agent', 'Appointment booking into your calendar', 'Multilingual answers for diverse Canadian cities', 'Call summaries sent to your phone and CRM'],
    result: 'No missed leads, faster bookings and more of your evenings back.' },
  { id: 'automation', icon: 'flow', name: 'Business automation', tagline: 'Connect your tools and stop doing the same task twice.',
    body: 'We map how leads, jobs and payments move through your business, then automate the repetitive steps: lead routing, quotes, appointment reminders, Interac and card payment links, review requests and reporting. Messages are set up to respect Canada\'s Anti-Spam Legislation (CASL) consent rules.',
    includes: ['CRM setup and automatic lead routing', 'Quotes, reminders and CASL-compliant follow-ups', 'Invoices with payment links', 'Review requests after every completed job', 'Dashboards that update on their own'],
    result: 'Hours saved every week, fewer errors and quicker service.' },
  { id: 'social', icon: 'chat', name: 'Social media marketing', tagline: 'Stay visible and trusted where your customers scroll.',
    body: 'A steady rhythm of posts, short videos and targeted Facebook and Instagram ads keeps your business in front of local customers, brings past visitors back and supports the reviews and searches that drive your Google rankings.',
    includes: ['Content calendar and branded post designs', 'Short-form video and reels', 'Facebook and Instagram ads', 'Retargeting of website visitors', 'Comment and message management'],
    result: 'A brand people recognize, and cheaper repeat business.' },
  { id: 'management', icon: 'chart', name: 'Monthly business management', tagline: 'One team running your whole online presence.',
    body: 'Website updates, Google profile, ads, SEO, social media and reporting handled every month by one accountable team, so you can spend your time on the work and the customers rather than on platforms and passwords.',
    includes: ['Website updates and maintenance', 'Google Business Profile management', 'Ads, SEO and social in one plan', 'Monthly strategy call', 'One report with the numbers that matter'],
    result: 'Steady growth without hiring and managing an in-house marketing team.' },
  { id: 'software', icon: 'code', name: 'Custom software development', tagline: 'Software shaped around the way you work.',
    body: 'From job tracking and inventory to custom CRMs for multi-location teams, our developers build software that fits your process, hosted securely and supported after launch.',
    includes: ['Requirements and process mapping', 'Custom CRM and job management', 'Secure cloud hosting', 'Ongoing support and updates', 'Staff training'],
    result: 'Systems that keep up as you add staff, vehicles and locations.' },
  { id: 'graphics', icon: 'brush', name: 'Graphic design & branding', tagline: 'A look that matches the quality of your work.',
    body: 'Logos, brand kits, vehicle wrap artwork, ad creatives and social graphics, included with our services so your website, ads, trucks and profiles all look like the same professional company.',
    includes: ['Logo and brand kit', 'Ad and social media creatives', 'Website graphics and banners', 'Vehicle wrap and print artwork', 'Video thumbnails and covers'],
    result: 'A consistent, professional image everywhere customers meet you.' },
]

export const CA_HOME_FAQ: Faq[] = [
  { q: 'How much does local SEO cost for a small business in Canada?', a: 'It depends on your trade, how many locations you serve and how competitive your city is. A plumber in Lethbridge needs less work than a personal injury firm in downtown Toronto. We give you a fixed monthly price in Canadian dollars after a free audit of your Google profile, website and competitors, so you know the cost before anything starts.' },
  { q: 'How much do Google Ads cost in Canada?', a: 'Canadian account averages run roughly $4–12 a click for home services, $3–10 for dental and healthcare, $8–30 or more for legal and under $2 for restaurants (Consultus Digital, 2026). Headline keywords in Toronto and Calgary cost much more: $15–50 for trades and $80–150 for personal injury. Our calculator uses these Canadian figures in CAD.' },
  { q: 'Is $10 a day enough for Google Ads in Canada?', a: 'Rarely for a service business. At about $9 a click, $300 a month buys roughly 33 clicks, which is often two or three enquiries. Most Canadian local businesses that see steady results invest $1,000 to $5,000 a month in ad spend. The calculator shows what different budgets can return in your category.' },
  { q: 'Are Local Services Ads available in Canada?', a: 'Yes. Local Services Ads run in Canada for trades such as HVAC, plumbing, electrical and roofing, and for several professional services. Since October 2025 verified businesses show a single Google Verified checkmark. In Toronto, leads average about $39 for electricians, $51 for HVAC and $57 for plumbers (Creative Scope, 2026).' },
  { q: 'How long does local SEO take to work?', a: 'Most Canadian businesses see map rankings and calls start to move within two to three months, with stronger gains by months four to six. Toronto and Calgary trades with many established competitors can take longer, which is why we usually pair SEO with ads for leads in the meantime.' },
  { q: 'Do you work in French?', a: 'Yes. We can build French pages, run French Google Ads campaigns and set up AI agents that answer in French. French campaigns often have lower click costs, which is useful for businesses serving Quebec, Ottawa–Gatineau or bilingual customers.' },
  { q: 'Do you have a team in Canada?', a: 'Yes. Jarz Digital\'s Canadian team is based in Calgary, Alberta. We work with businesses across Canada through video calls, shared dashboards and clear monthly reporting.' },
  { q: 'Can you build our website and run the marketing as well?', a: 'Yes. Our own designers and developers build websites and web apps, and the same team runs your SEO, ads, AI agents and social media. One team means the website is built to convert the traffic we send to it.' },
]

const geo = (lat: number, lng: number) => ({ lat, lng })

export const CA_CITIES: City[] = [
  { id: 'toronto', slug: 'toronto-on', name: 'Toronto', state: 'Ontario', stateCode: 'ON', region: 'Greater Toronto Area',
    brand: 'SEO company in Toronto',
    title: 'SEO Company Toronto: Local SEO & Google Ads | Jarz Digital',
    description: 'SEO company in Toronto for local businesses. Local SEO, Google Ads, AI SEO and web design that bring calls across the GTA. Free audit, prices in CAD.',
    h1: 'SEO company in Toronto for local and service businesses',
    kicker: 'Toronto, ON · Local SEO · Google Ads · AI SEO · Web design',
    intro: [
      'Jarz Digital is a Toronto SEO company and Google Ads agency for local businesses across the GTA. We put trades, clinics, law firms, auto shops and restaurants into the Google Maps top three, run paid search that is judged by booked jobs and answer every enquiry with AI agents, so the leads you pay for turn into customers.',
      'Toronto has the most expensive local search auctions in Canada. Headline home-service keywords cost $15–30 a click, and personal injury terms can pass $100. In a market like that, wasted clicks and missed calls are the real cost of marketing. Our job is to remove both, and to build organic rankings that lower your cost per customer over time.',
    ],
    market: [
      { h: 'Neighbourhood-level visibility', p: 'Customers in Etobicoke, North York, Scarborough and the downtown core see different map results. We build neighbourhood pages, service-area settings and review signals so you rank where your crews actually go, not just near your address.' },
      { h: 'Paid search that respects a Toronto budget', p: 'Downtown and Toronto proper cost more than the suburbs. We split campaigns by area, block irrelevant searches weekly and send traffic to landing pages built for calls, so a $9 click has a real chance of becoming a job.' },
      { h: 'Local Services Ads for GTA trades', p: 'For HVAC, plumbing, electrical and drain work we pair Google Ads with Local Services Ads, where Toronto leads average about $51, $57, $39 and $59 respectively. We handle the licence, insurance and background-check paperwork so you get verified quickly.' },
    ],
    areas: ['Downtown Toronto', 'North York', 'Scarborough', 'Etobicoke', 'East York', 'York', 'Midtown', 'The Danforth', 'Leslieville', 'Liberty Village', 'Richmond Hill', 'Markham', 'Vaughan', 'Pickering', 'Ajax', 'Oakville'],
    calcCat: 'hvac',
    proof: { img: '/img/ca-richmond-hill-auto-repair-google-maps-1st-place.webp', alt: 'Google results for "auto repair in richmond hill" with a Jarz Digital client ranked first in the map results, 5.0 stars from 492 reviews', caption: '"auto repair in richmond hill": our GTA client is the first business in Google\'s map results, rated 5.0 from 492 reviews (client name hidden).', width: 1600, height: 1121 },
    faq: [
      { q: 'How much do Google Ads cost in Toronto?', a: 'Toronto runs the hottest auctions in Canada. Headline home-service keywords typically cost $15–30 a click and $30–50 in peak season, dental and med spa terms $8–25, and personal injury $80–150 (Creative Scope, 2026). Long-tail and neighbourhood keywords cost far less, which is where a well-built account finds its margin.' },
      { q: 'Can you rank my Toronto business across the whole GTA?', a: 'We can help you rank well beyond your address by building service-area and neighbourhood pages, earning reviews that mention the areas you serve and setting your Google Business Profile correctly. Proximity still matters, so we focus first on the parts of the GTA that bring the most profitable work.' },
      { q: 'Do you offer SEO for Toronto dentists and clinics?', a: 'Yes. Dental, physiotherapy, RMT and med spa clinics are a large part of our work. We optimize each practitioner\'s profile, build treatment pages within your regulatory college\'s advertising rules and add online booking and AI call answering.' },
    ],
    keywords: ['seo company toronto', 'seo services toronto', 'local seo company toronto', 'seo agency toronto', 'web design company toronto', 'digital marketing agency toronto', 'ppc agency toronto', 'ai seo agency toronto'],
    geo: geo(43.6532, -79.3832) },
  { id: 'brampton', slug: 'brampton-on', name: 'Brampton', state: 'Ontario', stateCode: 'ON', region: 'Peel Region',
    brand: 'SEO company in Brampton',
    title: 'SEO Company Brampton: Local SEO & Web Design | Jarz Digital',
    description: 'SEO company in Brampton offering SEO services, local SEO, Google Ads, multilingual AI agents and web design for businesses across Peel Region.',
    h1: 'SEO company in Brampton for local SEO services that bring customers',
    kicker: 'Brampton, ON · Local SEO · Google Ads · Web design · AI agents',
    intro: [
      'Jarz Digital is an SEO company in Brampton providing SEO services for businesses that depend on local customers: immigration consultants, truck driving schools, auto repair shops, lawyers, clinics, restaurants and contractors. We combine local SEO, Google Ads, multilingual AI agents and fast websites into one plan built around how Brampton actually searches.',
      'Brampton is one of the youngest and most diverse cities in Canada, and many residents search in English, Punjabi, Hindi or Urdu. Businesses that speak to customers in their own language, answer the phone quickly and collect steady reviews win a larger share of every search. We build exactly that system.',
    ],
    market: [
      { h: 'Multilingual search and service', p: 'We create pages, ads and AI receptionist scripts in the languages your customers use, so a family searching for an immigration consultant or a driving school feels understood from the first click.' },
      { h: 'Competitive professional services', p: 'Immigration, legal and real estate keywords are expensive in Peel Region. We focus budgets on high-intent searches, show credentials such as CICC and Law Society licences clearly and track which ads bring signed clients.' },
      { h: 'Trucking and logistics hub', p: 'With Highway 410, the 407 and major distribution centres nearby, Brampton has strong demand for AZ licence training, truck repair and logistics services. We separate driver-recruitment searches from customer searches so budgets are not wasted.' },
    ],
    areas: ['Downtown Brampton', 'Bramalea', 'Springdale', 'Heart Lake', 'Mount Pleasant', 'Castlemore', 'Sandalwood', 'Fletcher\'s Meadow', 'Gore Meadows', 'Credit Valley', 'Caledon', 'Malton'],
    calcCat: 'immigration',
    proof: { img: '/img/ca-google-business-profile-1845-calls-a-month.webp', alt: 'Google Business Profile performance report showing 1,845 calls made from a client\'s Business Profile in June 2026', caption: '1,845 phone calls in one month from a client\'s Google Business Profile, June 2026 (client name hidden).', width: 1600, height: 839 },
    faq: [
      { q: 'Do you offer SEO services in Brampton for immigration consultants?', a: 'Yes. Immigration consulting is one of the most competitive categories in Brampton. We build service pages for each pathway you handle, run focused Google Ads, show your CICC licence details where required and set up an AI agent that answers enquiries in English, Punjabi or Hindi.' },
      { q: 'Can you run Google Ads in Punjabi or Hindi for Brampton customers?', a: 'Google Ads supports Punjabi and Hindi language targeting, and many Brampton customers also search in English with their own phrasing. We test both, and keep whichever brings cheaper, better-qualified leads.' },
      { q: 'Do you build websites for Brampton businesses?', a: 'Yes. We design fast, mobile-first websites with click-to-call, WhatsApp chat and booking, built to rank for Brampton searches from the day they launch.' },
    ],
    keywords: ['seo company brampton', 'seo services brampton', 'local seo brampton', 'seo agency brampton', 'web design company brampton', 'digital marketing agency brampton', 'digital marketing services brampton', 'google ads brampton'],
    geo: geo(43.7315, -79.7624) },
  { id: 'mississauga', slug: 'mississauga-on', name: 'Mississauga', state: 'Ontario', stateCode: 'ON', region: 'Peel Region',
    brand: 'Mississauga SEO agency',
    title: 'Mississauga SEO Company & Google Ads Agency | Jarz Digital',
    description: 'Mississauga SEO agency for clinics, trades, logistics and local shops. Local SEO, Google Ads, AI SEO and website development across Peel. Free audit.',
    h1: 'Mississauga SEO agency for clinics, trades and local businesses',
    kicker: 'Mississauga, ON · Local SEO · Google Ads · Website development',
    intro: [
      'Jarz Digital is a Mississauga SEO company and Google Ads agency for local and service businesses across Peel Region. We help dentists, physiotherapists, RMT clinics, home service companies, logistics firms and restaurants rank on Google Maps, win more calls from paid search and convert visitors with fast, well-built websites.',
      'Mississauga is a city of distinct communities, from Port Credit and Streetsville to Square One and Meadowvale, with a large business district around the airport. Customers search by neighbourhood and compare reviews carefully. We build the local relevance, reputation and response speed that decide who they call.',
    ],
    market: [
      { h: 'Neighbourhood searches', p: 'Searches such as "dentist Erin Mills", "physiotherapy Meadowvale" and "physiotherapy near Square One" show how locally Mississauga customers think. We create neighbourhood pages and profile signals that match those searches.' },
      { h: 'Healthcare and wellness', p: 'Clinics compete hard for new patients. We emphasize credentials, insurance and direct billing information, reviews and online booking, and add an AI receptionist that books appointments after hours.' },
      { h: 'Logistics and B2B services', p: 'Mississauga is one of Canada\'s largest logistics and corporate hubs. For trucking companies, warehouses and B2B services we build lead-generation campaigns that separate customer searches from job seekers.' },
    ],
    areas: ['Port Credit', 'Streetsville', 'Meadowvale', 'Erin Mills', 'Square One / City Centre', 'Cooksville', 'Malton', 'Clarkson', 'Lorne Park', 'Churchill Meadows', 'Hurontario', 'Heartland', 'Oakville', 'Milton'],
    calcCat: 'dentist',
    proof: { img: '/img/ca-richmond-hill-massage-clinic-google-first-result.webp', alt: 'Google results showing a Jarz Digital client massage clinic as the top result with sitelinks and a Google Business Profile rated 4.6 from 442 reviews', caption: 'A GTA massage and physiotherapy clinic we support: top result with sitelinks and a full Google profile, 4.6 stars from 442 reviews (client name hidden).', width: 1600, height: 1077 },
    faq: [
      { q: 'What does a Mississauga SEO agency do differently?', a: 'We plan around the city\'s neighbourhoods and its mix of residential and business districts. That means neighbourhood pages, reviews that mention the areas you serve, and separate strategies for consumer and B2B customers.' },
      { q: 'Can you help my clinic get more new patients in Mississauga?', a: 'Yes. We optimize each practitioner\'s Google profile, build treatment and condition pages, highlight direct billing and booking, and set up reminders and review requests that keep schedules full.' },
      { q: 'Do you offer website development in Mississauga?', a: 'Yes. Our developers build custom websites and web apps, including booking systems and client portals, designed to load quickly and rank well.' },
    ],
    keywords: ['seo company mississauga', 'mississauga seo agency', 'seo services mississauga', 'local seo mississauga', 'web design mississauga', 'website development mississauga', 'digital marketing agency mississauga', 'google ads agency mississauga'],
    geo: geo(43.589, -79.6441) },
  { id: 'calgary', slug: 'calgary-ab', name: 'Calgary', state: 'Alberta', stateCode: 'AB', region: 'Calgary region',
    brand: 'SEO company in Calgary',
    title: 'SEO Company Calgary: Google Ads & Web Design | Jarz Digital',
    description: 'Calgary SEO company with a local team. Local SEO, Google Ads, AI agents and web design for Calgary trades, clinics and shops. #1 Maps results. Free audit.',
    h1: 'Calgary SEO company with a local team and proven #1 results',
    kicker: 'Calgary, AB · Local SEO · Google Ads · Web design · AI agents',
    intro: [
      'Jarz Digital is a Calgary SEO company with a team based in the city, working with businesses across Calgary and the surrounding region. We provide local SEO services, Google Ads management, AI SEO, AI receptionists and web design for roofers, HVAC and plumbing companies, renovators, clinics, salons and local shops. A Calgary beauty and spa business we support appears first in Google\'s map results for "beauty & spa in calgary", directly beneath the only paid ad.',
      'Calgary is a fast-growing city with dramatic seasons. Hail in summer, chinooks and cold snaps in winter and steady population growth create sudden spikes in demand. The businesses that win are ready before the spike: strong map rankings, campaigns prepared in advance and a phone that always gets answered.',
    ],
    market: [
      { h: 'Hail and weather spikes', p: 'Roofing, siding, eavestrough, auto body and glass searches surge after every summer hail storm, and furnace repair spikes in the first cold snap. We prepare storm pages and campaigns ahead of time and scale them within hours.' },
      { h: 'Quadrant-based targeting', p: 'Calgary customers search by quadrant and community: NW, NE, SW and SE, Beltline, Kensington, Seton or Airdrie. We build pages and ad targeting around the areas you actually serve.' },
      { h: 'Local team, local knowledge', p: 'Because part of our team is based in Calgary, we understand the neighbourhoods, the seasons and the competition, and we can plan campaigns around local events such as Stampede.' },
    ],
    areas: ['Downtown Calgary', 'Beltline', 'Kensington', 'Inglewood', 'Bridgeland', 'Mission', 'Seton', 'Mahogany', 'Tuscany', 'Evanston', 'Saddle Ridge', 'Panorama Hills', 'Airdrie', 'Cochrane', 'Okotoks', 'Chestermere'],
    calcCat: 'roofing',
    proof: { img: '/img/ca-calgary-beauty-spa-google-maps-1st-place.webp', alt: 'Google results for "beauty & spa in calgary" with a Jarz Digital client as the first business listing directly beneath the sponsored ad, rated 4.9 from 90 reviews', caption: '"beauty & spa in calgary": our client is the first business listing, directly beneath the only paid ad, rated 4.9 from 90 reviews (client name hidden).', width: 1600, height: 941 },
    faq: [
      { q: 'Do you have a team in Calgary?', a: 'Yes. Part of the Jarz Digital team is based in Calgary, so we know the city\'s neighbourhoods, seasons and competition first-hand. We meet clients by video call and work with businesses across Calgary and southern Alberta.' },
      { q: 'How much do Google Ads cost in Calgary?', a: 'Alberta account averages run about $5.50–9.50 a click for home services and renovation, $9–15 for legal and $3.50–6.50 for healthcare and dentistry (Hetman, 2026). Headline Calgary terms cost more: plumbing $15–45, HVAC $15–50 and roofing $15–40 (ScopeX Media, 2026).' },
      { q: 'Can you help Calgary roofers and contractors after hail storms?', a: 'Yes. We build hail-damage and insurance-claim pages before the season, launch campaigns within hours of a storm and set up an AI receptionist to book inspections while call volume is high.' },
    ],
    keywords: ['seo company calgary', 'seo services calgary', 'local seo services calgary', 'web design calgary', 'website design calgary', 'digital marketing agency calgary', 'google ads calgary', 'small business marketing calgary'],
    geo: geo(51.0447, -114.0719) },
  { id: 'alberta', slug: 'alberta', name: 'Alberta', state: 'Alberta', stateCode: 'AB', region: 'Province of Alberta', display: 'Alberta',
    brand: 'Alberta SEO agency',
    title: 'Alberta SEO Agency: Local SEO & Google Ads | Jarz Digital',
    description: 'Alberta SEO agency for local businesses in Edmonton, Red Deer, Lethbridge and beyond. Local SEO, Google Ads, AI agents and web design. Free audit.',
    h1: 'Alberta SEO agency for local businesses in every corner of the province',
    kicker: 'Alberta · Edmonton · Red Deer · Lethbridge · Local SEO · Google Ads',
    intro: [
      'Jarz Digital is an Alberta SEO agency with a team in Calgary, helping local businesses in Edmonton, Red Deer, Lethbridge, Airdrie, Grande Prairie, Medicine Hat and Fort McMurray grow through local SEO, Google Ads, AI agents and web design. Many of our clients serve several towns, so we build visibility for every community they cover.',
      'Alberta is one of the fastest-growing provinces in Canada, and new residents search for trades, clinics and services they have never used before. Smaller Alberta markets often have cheaper clicks and fewer strong competitors, which means a business that invests now can own its category for years.',
    ],
    market: [
      { h: 'Multi-town service areas', p: 'A contractor in Red Deer may serve Lacombe, Sylvan Lake and Blackfalds. We build town pages, service-area settings and citations so you appear across your whole territory, not only where your office sits.' },
      { h: 'Lower costs outside the big cities', p: 'Clicks in smaller Alberta markets usually cost less than in Calgary and Edmonton. We use that advantage to bring leads at a lower cost while local SEO builds lasting rankings.' },
      { h: 'Industries that power Alberta', p: 'Energy services, trucking, agriculture equipment, construction and the trades that support them all need visibility. We build B2B and consumer campaigns that speak to each audience separately.' },
    ],
    areas: ['Edmonton', 'Calgary', 'Red Deer', 'Lethbridge', 'Airdrie', 'St. Albert', 'Sherwood Park', 'Grande Prairie', 'Medicine Hat', 'Fort McMurray', 'Spruce Grove', 'Leduc', 'Okotoks', 'Cochrane', 'Canmore', 'Camrose'],
    calcCat: 'heating',
    proof: { img: '/img/ca-online-store-122k-sales-woocommerce-report.webp', alt: 'WooCommerce sales report for an online store we work with showing $122,458 in gross sales and 1,859 orders over eight months', caption: 'Online store sales report: $122,458 gross sales, 1,859 orders and $0 in refunds over eight months (store name hidden).', width: 1600, height: 773 },
    faq: [
      { q: 'Do you work with Alberta businesses in Edmonton?', a: 'Yes. We work with Edmonton businesses in the trades, healthcare, legal services, automotive and retail, as well as companies in St. Albert, Sherwood Park, Spruce Grove and Leduc. Our Alberta team is based in Calgary and works with clients across the province by video call.' },
      { q: 'Is SEO worth it in smaller Alberta towns?', a: 'Often more than in the big cities. There are fewer strong competitors, so a well-optimized Google Business Profile, a fast website and steady reviews can put you at the top of the map results quickly and keep you there.' },
      { q: 'Do you understand Alberta privacy rules?', a: 'Yes. Private businesses in Alberta follow the Personal Information Protection Act (PIPA). Our forms, AI agents and automations collect only the information you need, with clear consent and secure storage.' },
    ],
    keywords: ['alberta seo agency', 'seo company alberta', 'digital marketing alberta', 'seo edmonton', 'web design edmonton', 'web design company edmonton', 'digital marketing agencies edmonton', 'local seo red deer'],
    geo: geo(53.5461, -113.4938) },
]

export const CA_HOME = {
  title: 'Local SEO Services & Google Ads Agency Canada | Jarz Digital',
  description: 'Local SEO services, Google Ads, AI SEO and AI agents for Canadian local businesses in Toronto, Brampton, Mississauga, Calgary and across Alberta.',
}

export const CA_PROOF = [
  { img: '/img/ca-richmond-hill-auto-repair-google-maps-1st-place.webp', alt: 'Google results for "auto repair in richmond hill" with a Jarz Digital client ranked first in the map results', city: 'Richmond Hill, ON', search: 'auto repair in richmond hill', note: 'First in the map results, rated 5.0 from 492 reviews, ahead of shops with up to 978 reviews', width: 1600, height: 1121, badge: '#1 · Richmond Hill, ON' },
  { img: '/img/ca-calgary-beauty-spa-google-maps-1st-place.webp', alt: 'Google results for "beauty & spa in calgary" with a Jarz Digital client as the first business listing under the sponsored ad', city: 'Calgary, AB', search: 'beauty & spa in calgary', note: 'First business listing, directly beneath the only paid ad, rated 4.9', width: 1600, height: 941, badge: '#1 · Calgary, AB' },
  { img: '/img/ca-google-business-profile-1845-calls-a-month.webp', alt: 'Google Business Profile performance showing 1,845 calls in June 2026', city: 'Ontario', search: 'Calls from Google Business Profile', note: '1,845 calls in a single month, June 2026', width: 1600, height: 839, badge: '1,845 calls · 1 month' },
  { img: '/img/ca-richmond-hill-massage-clinic-google-first-result.webp', alt: 'Google results with a Jarz Digital client clinic as the top result with sitelinks, rated 4.6 from 442 reviews', city: 'Richmond Hill, ON', search: 'Massage and physiotherapy clinic', note: 'Top result with sitelinks and a full profile, 4.6 stars from 442 reviews', width: 1600, height: 1077, badge: '442 reviews · 4.6★' },
  { img: '/img/ca-online-store-122k-sales-woocommerce-report.webp', alt: 'WooCommerce report showing $122,458 gross sales and 1,859 orders for an online store we work with', city: 'E-commerce', search: 'Online store sales report', note: '$122,458 gross sales and 1,859 orders, $0 refunded', width: 1600, height: 773, badge: '$122,458 sales' },
  { img: '/img/ca-online-store-85k-sales-overview.webp', alt: 'WooCommerce overview showing $85,396 total sales and 1,285 orders after launch in July', city: 'E-commerce', search: 'Online store overview', note: '$85,396 in sales and 1,285 orders from a July launch', width: 1187, height: 627, badge: '$85,396 sales' },
]

export const CA_INDUSTRIES = ['HVAC & furnace', 'Plumbing & drains', 'Roofing & eavestroughs', 'Electricians', 'Renovation & basements', 'Snow removal', 'Landscaping', 'Cleaning services', 'Movers', 'Pest control', 'Auto repair', 'Auto body & collision', 'Tires & glass', 'Towing', 'Dentists', 'Physiotherapy', 'RMT massage', 'Chiropractors', 'Med spas', 'Veterinarians', 'Personal injury lawyers', 'Family lawyers', 'Immigration consultants', 'Real estate', 'Mortgage brokers', 'Truck driving schools', 'Restaurants', 'Salons & barbers', 'Gyms & studios']
