import type { Industry } from "@/types/content";

export type SeedIndustry = Omit<Industry, "_id" | "services"> & { serviceSlugs: string[] };

/**
 * The 16 industries listed under "Work by Industry" on jarzdigital.com.
 * The original site listed names only (every link pointed to "#"), so the
 * explanatory copy below is drafted from Jarz Digital's existing service
 * descriptions and flagged `needsReview` so the team can refine it in the CMS.
 */
const local = ["local-seo", "website-development", "business-management"];

const make = (
  order: number,
  slug: string,
  name: string,
  headline: string,
  icon: string,
  intro: string,
  challenges: [string, string][],
  solutions: [string, string][],
  serviceSlugs: string[] = local,
): SeedIndustry => ({
  slug,
  name,
  headline,
  icon,
  intro,
  challenges: challenges.map(([title, description]) => ({ title, description })),
  solutions: solutions.map(([title, description]) => ({ title, description })),
  serviceSlugs,
  order,
  published: true,
  needsReview: true,
  seo: {},
});

export const industrySeed: SeedIndustry[] = [
  make(1, "auto-repair", "Auto Repair", "Auto Repair Web Design", "wrench",
    "Drivers search for a repair shop when something breaks — usually on their phone, usually nearby. We help auto repair and custom car shops win those searches.",
    [["Urgent, local searches", "Customers choose from the first few shops they see on Google Maps."], ["Trust before the first call", "Reviews, photos and a clear website decide who gets the booking."], ["Seasonal demand", "Promotions need to reach local drivers at the right time."]],
    [["Google Maps ranking", "Google Business Profile optimization, citations and local backlinks."], ["Conversion-ready website", "Mobile-first pages with click-to-call, services and quote forms."], ["Always-on presence", "Monthly management of SEO, social posts and profile updates."]],
    ["local-seo", "website-development", "business-management", "google-ads"]),
  make(2, "banking", "Banking", "Bank Web Design", "landmark",
    "Banks and credit providers need digital experiences that feel secure, perform fast and make complex products easy to understand.",
    [["Security expectations", "Visitors judge credibility instantly from design and performance."], ["Complex product information", "Rates, accounts and services must be clear and accessible."], ["Local branch discovery", "Branch pages need to rank in the communities you serve."]],
    [["Secure, fast websites", "SSL, regular security updates and performance optimization."], ["Clear information architecture", "Structured pages built for scanning and accessibility."], ["Custom web applications", "Portals and dashboards built to your requirements."]],
    ["website-development", "web-application-development", "seo"]),
  make(3, "corporate", "Corporate", "Corporate Web Design", "building-2",
    "Corporate websites carry the brand for every audience — clients, partners, recruits and investors. They need to be polished, fast and easy to maintain.",
    [["Many audiences, one site", "Clients, candidates and partners all need different paths."], ["Brand consistency", "Every page and campaign must reflect the brand."], ["Keeping content current", "Updates stall when every change needs a developer."]],
    [["Premium custom design", "Brand-aligned design with professional typography and imagery."], ["Content management", "An easy-to-use CMS for your team."], ["Ongoing management", "Website updates, content and reporting handled monthly."]],
    ["website-development", "seo", "business-management"]),
  make(4, "construction", "Construction", "Construction Web Design", "hard-hat",
    "Contractors and construction firms win work on reputation and visibility. We make sure the right projects find you on Google.",
    [["High-value local searches", "Commercial and residential clients search by service and city."], ["Showcasing past work", "Prospects want to see completed projects before they call."], ["Lead quality", "You need qualified inquiries, not tire-kickers."]],
    [["Local & website SEO", "Rank for the services and areas you cover."], ["Project galleries", "Portfolio pages that show your craftsmanship."], ["Targeted ads", "Google Ads campaigns focused on high-intent searches."]],
    ["local-seo", "seo", "website-development", "google-ads"]),
  make(5, "dental", "Dental", "Dental Web Design", "smile",
    "Patients choose a dentist close to home, with great reviews and easy booking. We help practices show up — and get chosen.",
    [["“Dentist near me” competition", "The map pack decides which practice gets the call."], ["Reputation", "Reviews heavily influence new patients."], ["Booking friction", "Patients leave if booking or calling is difficult on mobile."]],
    [["Google Business Profile", "Optimization, regular updates and review management setup."], ["Patient-friendly website", "Mobile-first design with clear services and booking."], ["Social media", "Consistent, branded posts that build community trust."]],
    ["local-seo", "website-development", "social-media-marketing"]),
  make(6, "family-law", "Family Law", "Family Law Attorney Web Design", "scale",
    "People looking for a family lawyer are making difficult decisions. Your website must feel trustworthy, empathetic and easy to act on.",
    [["Sensitive decisions", "Clients need reassurance before they reach out."], ["Competitive local search", "Legal keywords are some of the most competitive online."], ["Clear practice areas", "Visitors need to quickly find the help they need."]],
    [["Trust-building design", "Professional design with clear calls to action."], ["Local SEO", "Rank in your city for your practice areas."], ["Google Ads", "Reach people actively searching for legal help."]],
    ["website-development", "local-seo", "google-ads"]),
  make(7, "financial-advisors", "Financial Advisors", "Financial Advisor Web Design", "chart-line",
    "Financial advisors grow through trust and referrals. A strong digital presence makes it easy for prospects to understand your approach and book a conversation.",
    [["Credibility online", "Prospects research advisors thoroughly before contacting them."], ["Explaining services clearly", "Complex offerings need simple, structured pages."], ["Consistent visibility", "Staying top-of-mind between referrals."]],
    [["Professional website", "Clear service pages and consultation booking."], ["SEO content", "SEO-optimized articles that answer client questions."], ["Social media", "Branded content that keeps you visible."]],
    ["website-development", "seo", "social-media-marketing"]),
  make(8, "gym", "Gym", "Gym Web Design", "dumbbell",
    "Gyms and fitness studios compete on location, community and energy. We help you capture local searches and turn visitors into members.",
    [["Local competition", "Members usually choose a gym close to home or work."], ["Showing the experience", "Classes, trainers and facilities need to shine online."], ["Membership sign-ups", "Converting interest into trials and memberships."]],
    [["Local SEO", "Rank on Google Maps in your neighbourhood."], ["Social media marketing", "Engaging posts on Instagram, Facebook and TikTok."], ["Ads & promotions", "Targeted Meta and Google campaigns for launches and offers."]],
    ["local-seo", "social-media-marketing", "google-ads"]),
  make(9, "healthcare", "Healthcare", "Healthcare Web Design", "heart-pulse",
    "Clinics and healthcare providers need patients to find them locally and feel confident booking. We combine local search, clear websites and consistent social content.",
    [["Local patient discovery", "Patients search by treatment and location."], ["Communicating services", "Physiotherapy, chiropractic, massage and more — each needs clarity."], ["Staying active online", "Wellness programs and promotions need consistent visibility."]],
    [["Local SEO & Google Business Profile", "Optimized profiles, citations and reviews."], ["Clinic websites", "Clear treatment pages with booking and calls to action."], ["Monthly management", "Website, SEO and social media handled as one."]],
    ["local-seo", "business-management", "social-media-marketing", "website-development"]),
  make(10, "hvac", "HVAC", "HVAC Web Design", "thermometer-snowflake",
    "When the heat or AC fails, homeowners call the first reliable company they find. We make sure that’s you.",
    [["Emergency searches", "Urgent calls go to the top of the map pack."], ["Seasonal peaks", "Demand spikes with the weather."], ["Service-area coverage", "You need visibility across every city you serve."]],
    [["Local SEO", "Map citations, directions and local backlinks for each area."], ["Google Ads", "Campaigns that capture urgent, high-intent searches."], ["Fast mobile website", "Click-to-call and quote forms front and centre."]],
    ["local-seo", "google-ads", "website-development"]),
  make(11, "law-firms", "Law Firms", "Law Firm Web Design", "gavel",
    "Law firms need authoritative websites and strong search visibility across their practice areas and locations.",
    [["Highly competitive keywords", "Legal searches are expensive and crowded."], ["Authority and trust", "Clients evaluate expertise before contacting a firm."], ["Multiple practice areas", "Each area needs its own optimized page."]],
    [["Website SEO", "Practice-area pages optimized for search."], ["Local SEO", "Rank in the cities you serve."], ["Professional design", "A credible, fast and accessible website."]],
    ["seo", "local-seo", "website-development"]),
  make(12, "manufacturing", "Manufacturing", "Manufacturing Web Design", "factory",
    "Manufacturers need websites that explain capabilities clearly, generate qualified B2B inquiries and connect with operational systems.",
    [["Complex capabilities", "Buyers need specifications and processes explained clearly."], ["B2B lead generation", "Turning technical traffic into RFQs."], ["Disconnected systems", "Inventory and orders often live in separate tools."]],
    [["Capability-led websites", "Structured pages for products, processes and industries served."], ["Web applications", "Inventory, order management and custom portals."], ["Custom software", "Integrations with existing systems and automation."]],
    ["website-development", "web-application-development", "software-development"]),
  make(13, "plumbing", "Plumbing", "Plumber Web Design", "droplets",
    "Plumbing jobs start with a search on a phone. We help plumbers rank locally, look trustworthy and get the call.",
    [["Urgent local searches", "Customers call whoever appears first on Google Maps."], ["Reputation", "Reviews decide between near-identical options."], ["Service-area visibility", "Ranking in every town you cover."]],
    [["Google Maps ranking", "Profile optimization, citations and local backlinks."], ["Click-to-call website", "Fast mobile pages built to generate calls."], ["Google Ads", "Capture emergency searches instantly."]],
    ["local-seo", "website-development", "google-ads"]),
  make(14, "restaurants", "Restaurants", "Restaurant Web Design", "utensils-crossed",
    "Diners decide where to eat from Google Maps, menus and photos. We help restaurants get discovered and keep guests coming back.",
    [["Discovery on Maps", "“Near me” searches drive a large share of new diners."], ["Menus and ordering", "Guests expect an easy menu and ordering experience on mobile."], ["Staying top-of-mind", "Specials and events need consistent social promotion."]],
    [["Local SEO", "Google Business Profile optimization with photos and updates."], ["Restaurant websites", "Menu-first design with ordering and calls to action."], ["Social media", "Branded, appetising content across Facebook and Instagram."]],
    ["local-seo", "website-development", "social-media-marketing", "business-management"]),
  make(15, "real-estate", "Real Estate", "Real Estate Web Design", "house",
    "Agents and brokerages need to stand out in a crowded market with a strong personal brand, listings visibility and a steady stream of leads.",
    [["Standing out", "Buyers and sellers compare many agents online."], ["Lead generation", "Converting portal traffic into your own leads."], ["Consistent marketing", "Listings and market updates need regular promotion."]],
    [["Personal brand websites", "Professional design built to capture leads."], ["Local SEO", "Rank for neighbourhoods and communities you serve."], ["Ads & social", "Targeted campaigns for listings and open houses."]],
    ["website-development", "local-seo", "google-ads", "social-media-marketing"]),
  make(16, "venture-capital", "Venture Capital", "Venture Capital Web Design", "rocket",
    "Venture firms need a sharp, credible web presence that communicates their thesis and portfolio to founders and LPs.",
    [["Credibility with founders", "Founders research firms carefully before pitching."], ["Showcasing the portfolio", "Portfolio companies and thesis need to be presented clearly."], ["Easy updates", "News and portfolio changes should not need a developer."]],
    [["Premium custom design", "A polished, brand-aligned website."], ["Content management", "Manage portfolio, team and news yourself."], ["Custom web applications", "Deal-flow portals and dashboards when you need them."]],
    ["website-development", "web-application-development", "software-development"]),
];
