import type { ImageRef, Project } from "@/types/content";

export type SeedProject = Omit<Project, "_id" | "industry" | "services"> & {
  industrySlug?: string;
  serviceSlugs: string[];
};

const w = (file: string, alt: string): ImageRef => ({ src: `/images/work/${file}`, alt, width: 1137, height: 798 });
const wide = (file: string, alt: string): ImageRef => ({ src: `/images/work/${file}`, alt, width: 2274, height: 1596 });
const seoShot = (file: string, alt: string): ImageRef => ({ src: `/images/work/${file}`, alt, width: 1600, height: 1123 });
const ba = (file: string, alt: string): ImageRef => ({ src: `/images/before-after/${file}`, alt, width: 1600, height: 900 });

/**
 * Portfolio assembled from the project imagery published on jarzdigital.com.
 * The original site showed images only (no written case studies), so every
 * description is limited to what the published imagery shows and is flagged
 * `needsReview`. No results/metrics are claimed — add them in the CMS once
 * verified with each client.
 */
export const projectSeed: SeedProject[] = [
  {
    slug: "cravin-crabs",
    title: "Cravin’ Crabs — redesign, local search & social",
    client: "Cravin’ Crabs",
    location: "Baltimore, MD",
    industrySlug: "restaurants",
    serviceSlugs: ["website-development", "business-management", "social-media-marketing", "local-seo"],
    categories: ["web-development", "business-management", "social-media", "seo", "local-seo"],
    summary: "A new website, managed Google presence and social content for a family-run steamed-crab carry-out in Baltimore.",
    description:
      "<p>Cravin’ Crabs is a Baltimore carry-out known for steamed shrimp and live and steamed Maryland crabs. We replaced a dated, text-heavy site with a bold, photo-led design built around the menu and online ordering.</p><p>Alongside the website, Jarz Digital manages the business’s Google presence and social media, producing branded graphics and posts that keep the restaurant visible to local diners.</p>",
    coverImage: w("cravin-crabs-web.webp", "Cravin’ Crabs website shown on laptop, tablet and phone"),
    gallery: [
      wide("cravin-crabs-management.webp", "Cravin’ Crabs business management overview — website, Google and social profiles"),
      wide("cravin-crabs-social.webp", "Cravin’ Crabs social media content designed by Jarz Digital"),
      wide("cravin-crabs-seo.webp", "Cravin’ Crabs search ranking overview"),
      seoShot("cravin-crabs-seo-2.png", "Cravin’ Crabs local search ranking"),
    ],
    beforeAfter: ba("cravin-crabs.png", "Cravin’ Crabs website before and after the redesign"),
    technologies: [],
    results: [],
    featured: true,
    order: 1,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "rides-on-time",
    title: "Rides On Time — airport transportation brand",
    client: "Rides On Time",
    location: "San Diego, CA",
    serviceSlugs: ["website-development", "business-management", "social-media-marketing", "local-seo"],
    categories: ["web-development", "business-management", "social-media", "seo", "local-seo"],
    summary: "Website, Google Business Profile, Instagram and search visibility for a San Diego airport transportation and chauffeured car service.",
    description:
      "<p>Rides On Time provides airport transportation and chauffeured car service in San Diego. The new website leads with an instant booking form and a clear fleet overview, with dedicated pages for airport transfers, corporate travel and winery tours.</p><p>Jarz Digital also manages the brand’s Google Business Profile and Instagram, producing a consistent visual identity across every channel.</p>",
    coverImage: w("rides-on-time-web.webp", "Rides On Time website on desktop, tablet and phone"),
    gallery: [
      wide("rides-on-time-management.webp", "Rides On Time Google Business Profile, website and Instagram managed by Jarz Digital"),
      wide("rides-on-time-social.webp", "Rides On Time social media content"),
      wide("rides-on-time-seo.webp", "Rides On Time search ranking overview"),
    ],
    beforeAfter: ba("rides-on-time.png", "Rides On Time website before and after the redesign"),
    technologies: ["WordPress", "Google Business Profile", "Facebook", "Instagram"],
    results: [],
    featured: true,
    order: 2,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "pride-customizing",
    title: "Pride Customizing — Miami car customization",
    client: "Pride Customizing",
    location: "Miami, FL",
    industrySlug: "auto-repair",
    serviceSlugs: ["website-development", "business-management", "local-seo"],
    categories: ["web-development", "business-management", "seo", "local-seo"],
    summary: "A high-contrast website and ongoing search management for a Miami auto body and custom car shop.",
    description:
      "<p>Pride Customizing is a Miami auto body and custom car shop offering wraps, PPF film, star-light roofs and sound systems for all makes and models. The website puts a quote form right in the hero, followed by a photo gallery of completed builds.</p><p>Jarz Digital manages the shop’s ongoing search and profile presence as part of a monthly business management plan.</p>",
    coverImage: w("pride-customizing-web.webp", "Pride Customizing website on desktop, tablet and phone"),
    gallery: [
      wide("pride-customizing-management.webp", "Pride Customizing business management overview"),
      wide("pride-customizing-seo.webp", "Pride Customizing search ranking overview"),
    ],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: true,
    order: 3,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "yonge-rehab",
    title: "Yonge Rehab — multidisciplinary clinic",
    client: "Yonge Rehab",
    location: "Richmond Hill, ON",
    industrySlug: "healthcare",
    serviceSlugs: ["business-management", "website-development", "social-media-marketing", "local-seo"],
    categories: ["web-development", "business-management", "social-media", "local-seo"],
    summary: "A redesigned clinic website plus managed Google Business Profile and Instagram for a Richmond Hill physiotherapy and wellness clinic.",
    description:
      "<p>Yonge Rehab is a multidisciplinary clinic in Richmond Hill, Ontario offering physiotherapy, massage therapy, chiropractic care and acupuncture. The redesigned website presents each treatment clearly with prominent call and booking actions.</p><p>Jarz Digital manages the clinic’s Google Business Profile and Instagram, including branded campaigns for wellness programs and seasonal promotions.</p>",
    coverImage: wide("yonge-rehab-management.webp", "Yonge Rehab website, Google Business Profile and Instagram"),
    gallery: [wide("yonge-rehab-social.webp", "Yonge Rehab social media campaigns")],
    beforeAfter: ba("yonge-rehab.png", "Yonge Rehab website before and after the redesign"),
    technologies: ["WordPress", "Google Business Profile", "Facebook", "Instagram"],
    results: [],
    featured: true,
    order: 4,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "creative-tree-and-stump",
    title: "Creative Tree and Stump — service business growth",
    client: "Creative Tree and Stump LLC",
    serviceSlugs: ["website-development", "business-management", "social-media-marketing", "seo"],
    categories: ["web-development", "business-management", "social-media", "seo"],
    summary: "Website, search visibility and social media for a tree and stump service company.",
    description:
      "<p>Creative Tree and Stump LLC provides tree and stump services. Jarz Digital designed the company’s website and manages its search visibility and social media as part of an ongoing business management engagement.</p>",
    coverImage: w("creative-tree-web.webp", "Creative Tree and Stump website on desktop, tablet and phone"),
    gallery: [
      wide("creative-tree-management.webp", "Creative Tree and Stump business management overview"),
      wide("creative-tree-social.webp", "Creative Tree and Stump social media content"),
      wide("creative-tree-seo.webp", "Creative Tree and Stump search ranking overview"),
    ],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: true,
    order: 5,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "carhat",
    title: "CarHat — Bangladesh car marketplace",
    client: "CarHat.bd",
    location: "Bangladesh",
    serviceSlugs: ["web-application-development", "website-development"],
    categories: ["web-development"],
    summary: "A modern car marketplace for buying, selling and exploring new, used and reconditioned vehicles across Bangladesh.",
    description:
      "<p>CarHat.bd is an online car marketplace in Bangladesh where buyers can find new, used and reconditioned vehicles from verified dealers and private sellers.</p><p>The platform combines search by brand, model and location with dedicated buy and sell flows, dealer listings, ad posting for sellers and a blog — built mobile-first on Next.js.</p>",
    coverImage: w("carhat-web.jpg", "CarHat.bd car marketplace on laptop and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: ["Next.js"],
    results: [],
    websiteUrl: "https://carhat.bd/",
    featured: false,
    order: 6,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "shajgoj",
    title: "Shajgoj — online beauty store",
    client: "Shajgoj.bd",
    location: "Bangladesh",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "An e-commerce store for authentic makeup, skincare and haircare products with nationwide delivery in Bangladesh.",
    description:
      "<p>Shajgoj.bd sells authentic beauty products online in Bangladesh — makeup, skincare, haircare, K-beauty, fragrance and personal care.</p><p>The storefront organises a large catalogue by category and brand, with prominent search, promotional banners, deals and offers, and a streamlined bag and checkout — built on Next.js.</p>",
    coverImage: w("shajgoj-web.jpg", "Shajgoj.bd beauty store on laptop and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: ["Next.js"],
    results: [],
    websiteUrl: "https://shajgoj.bd/",
    featured: false,
    order: 7,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "korean-skincare",
    title: "KoreanSkincare.bd — K-beauty e-commerce",
    client: "KoreanSkincare.bd",
    location: "Bangladesh",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "A premium e-commerce store for authentic Korean skincare, with cash on delivery all over Bangladesh.",
    description:
      "<p>KoreanSkincare.bd brings authentic Korean skincare to Bangladesh — toners and essences, serums, sunscreens, cleansers, moisturizers, sheet masks and complete routine sets.</p><p>The editorial, product-led design pairs elegant typography with clear category navigation, best sellers, deals and a wishlist and account area — built on Next.js.</p>",
    coverImage: w("korean-skincare-web.jpg", "KoreanSkincare.bd store on laptop and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: ["Next.js"],
    results: [],
    websiteUrl: "https://koreanskincare.bd/",
    featured: false,
    order: 8,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "gadget-and-gear",
    title: "Gadget & Gear BD — premium tech store",
    client: "Gadget & Gear BD",
    location: "Bangladesh",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "An online store for smartphones, laptops, audio and smart devices, with flash deals, EMI options and nationwide delivery.",
    description:
      "<p>Gadget &amp; Gear BD is a tech store in Bangladesh for smartphones, laptops, earbuds and audio, smart watches, monitors and accessories.</p><p>The storefront features category-first navigation, flash deals, EMI information, new arrivals and pre-orders, order tracking and a wishlist — built on Next.js.</p>",
    coverImage: w("gadget-and-gear-web.jpg", "Gadget & Gear BD tech store on laptop and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: ["Next.js"],
    results: [],
    websiteUrl: "https://gadgetandgear.bd/",
    featured: false,
    order: 9,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "puff-picks",
    title: "Puff Picks — Dallas e-commerce store",
    client: "Puff Picks",
    location: "Dallas, TX",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "A full e-commerce storefront with category navigation, promotions and ongoing technical support.",
    description:
      "<p>Puff Picks is a Dallas retailer selling online. The new store organizes a large catalogue into clear categories with promotional tiles, best-seller sections and a multi-currency header. Jarz Digital continues to provide technical support for the store.</p>",
    coverImage: w("puff-picks-web.webp", "Puff Picks online store on desktop, tablet and phone"),
    gallery: [],
    beforeAfter: ba("puff-picks.png", "Puff Picks website before and after the redesign"),
    technologies: [],
    results: [],
    featured: false,
    order: 6,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "firewood-denver",
    title: "Firewood — Denver firewood delivery",
    client: "Firewood",
    location: "Denver, CO",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "A warm, conversion-focused website with pricing plans and a blog for a Denver firewood delivery service.",
    description:
      "<p>A Denver firewood delivery business needed a site that sells premium, kiln-dried firewood delivered to homes, cabins and businesses. The design pairs rich photography with simple pricing plans, a quality guarantee and a content blog.</p>",
    coverImage: w("fire-wood-web.webp", "Firewood delivery website on desktop, tablet and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: false,
    order: 7,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "quirky-cart",
    title: "Quirky Cart — online store",
    client: "Quirky Cart",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "A product-led e-commerce store covering fashion, home essentials and electronics.",
    description:
      "<p>Quirky Cart sells fashion, home essentials and electronics online. The store design highlights hero products, trust badges (free shipping, secure payment, gift certificates) and dense, browsable product grids.</p>",
    coverImage: w("quirky-cart-web.webp", "Quirky Cart store on desktop, tablet and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: false,
    order: 8,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "doorstep-spa",
    title: "Doorstep Spa — website design",
    client: "Doorstep Spa",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "Website design for a spa brand.",
    description: "<p>Website design and development for Doorstep Spa.</p>",
    coverImage: w("doorstep-spa-web.webp", "Doorstep Spa website on desktop, tablet and phone"),
    gallery: [],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: false,
    order: 9,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "richmond-hill-auto-repair",
    title: "Richmond Hill Auto Repair — managed growth",
    client: "Richmond Hill Auto Repair",
    industrySlug: "auto-repair",
    serviceSlugs: ["business-management", "local-seo"],
    categories: ["business-management", "local-seo"],
    summary: "Monthly business management — Google presence, website and social — for an auto repair shop.",
    description: "<p>Jarz Digital manages Richmond Hill Auto Repair’s digital presence as part of a monthly business management plan.</p>",
    coverImage: wide("richmond-hill-management.webp", "Richmond Hill Auto Repair business management overview"),
    gallery: [],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: false,
    order: 10,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "commercial-roofing-seo",
    title: "Commercial roofing — search rankings",
    client: "Commercial roofing contractor",
    industrySlug: "construction",
    serviceSlugs: ["seo", "local-seo"],
    categories: ["seo", "local-seo"],
    summary: "SEO and local search work for a commercial roofing contractor.",
    description: "<p>Search engine optimization and local search work for a commercial roofing contractor.</p>",
    coverImage: seoShot("commercial-roofing-seo.png", "Commercial roofing search ranking overview"),
    gallery: [],
    beforeAfter: null,
    technologies: [],
    results: [],
    featured: false,
    order: 11,
    published: true,
    needsReview: true,
    seo: {},
  },
  {
    slug: "blissful",
    title: "Blissful — website redesign",
    client: "Blissful",
    serviceSlugs: ["website-development"],
    categories: ["web-development"],
    summary: "A website redesign featured in the Jarz Digital before & after showcase.",
    description: "<p>A website redesign for Blissful, featured in our before &amp; after redesign showcase.</p>",
    coverImage: ba("blissful.png", "Blissful website before and after the redesign"),
    gallery: [],
    beforeAfter: ba("blissful.png", "Blissful website before and after the redesign"),
    technologies: [],
    results: [],
    featured: false,
    order: 12,
    published: true,
    needsReview: true,
    seo: {},
  },
];
